### ISSUE TITLE
Arduino Mega ADK with AT90USB82 

### ISSUE THREAD

**Issue by JasonBugeja** [kuwatay/mocolufa#2]
I have managed to flash the hex file to both my Funduino Mega and Arduino Uno R3 both with 16u2 USB chip and it works great.

I have another Arduino (Genuine) with AT90USB82 USB chip.  Can it be flashed with dualMoco.hex somehow? Flip is saying "address out of range"

**Comment by kuwatay** [comment]
The program will not fit on AT90USB82, as it has only 8kb flash.

**Comment by JasonBugeja** [comment]
Ok then, I will change the board for one that has 16u2 USB chip.  Thanks.

**Comment by JasonBugeja** [comment]
When I googled, I have found this http://morecatlab.akiba.coocan.jp/morecat_lab/MocoLUFA.html for 8u2, does it work on AT90USB82? Is there an updated version for 8kb chips?
